<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.201"/>
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15"/>
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0"/>
    <PackageVersion Include="Roslynator.Formatting.Analyzers" Version="4.15.0"/>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.22.0.136894"/>
  </ItemGroup>
</Project>
